### PR TITLE
Restyle of homepage

### PR DESCRIPTION
**Pull request by Mitcheljager**
I made a quick restyle of the homepage while still keeping the spirit of the old style. I hope to have made it all a bit easier to scroll through.

### CODE REVIEW

**Comment by Mitcheljager** [comment]
Few points:

- Using [BEM](http://getbem.com/introduction/) naming structure
- Compatible with modern browsers (IE10+)
- Fully responsive
- Fluid text sizes for easy reading on all screen sizes

**Comment by Mitcheljager** [comment]
Do with it what you like, any feedback welcome!

**Comment by Mitcheljager** [comment]
Added Semantics to create the following outline:

image

**Comment by domainzero** [comment]
alright this restyling is the dopest shit and i will probably merge it.

**Comment by Mitcheljager** [comment]
@domainzero Awesome, good to hear!

**Comment by domainzero** [comment]
Hit me with any more changes you wanna make. I'm going to try to swap the tables over to divs and then i gotta work on the routes page.

Thanks again for your work!

**Pull request merged**
