### PR TITLE
Multi-language support and highlight current week affixes - CORRECT version

### PR DESCRIPTION
**Pull request by amarques**

### CODE REVIEW

**Comment by domainzero** [comment]
Aaaaaaaaaaaaaaahhhhhhhhh this is so awesome!
I'll see if I can work in some buttons for language selection or maybe do some webserver redirection based on locale this evening.

**Comment by amarques** [comment]
The selection already getting from browser user language :)
If the user have a version not translated, the main/default language is en-english :)

**Comment by amarques** [comment]
I'm working on the finish touch right now. I think i will do 100% of that translation today. I add too a highlight selector to schedule m+ affixes table :)

**Comment by domainzero** [comment]
I noticed that, you're the the best!
It's appears to be auto translating to pt, even on my EN locale system.

I found  `langDefault: "pt"` set in `translate.js`, could that be causing it? I'm not familiar with translate.js

**Comment by amarques** [comment]
@domainzero u are right, i'm not familiar with github too :) i saw and have a old version.
I'm generating a new PR on a few minutes. So sorry about that.

**Pull request closed without merging**
