### PR TITLE
Adding French translation

### PR DESCRIPTION
**Pull request by Syel**
Adding French translation for 99.9% of strings. I don't think I made any typos, but if another french-speaking dev is around, feel free to double check :D

### CODE REVIEW

**Comment by domainzero** [comment]
Thanks a ton for this! I didn't even see this pull request.
I'll review it and get back to you shortly!

**Comment by domainzero** [comment]
Hey @Syel 

This is probably going to be a lot more tedious work, but can you set these up statically instead of relying on the existing jquery library?

I'm hoping to move off of having jquery on the site altogether. If you check out the `sections/en` folder you should see how I have the site laid out in English.

If you don't have time, I'll try to get this done soon:tm:

**Comment by Syel** [comment]
I'll try to find some time to do it that way!

If I understand the structure correctly, simply creating a `/fr` folder with translations respecting the same names as your files should be enough, or is there something I missed?

**Comment by domainzero** [comment]
I thought I responded to this.
Yeah, creating a `/fr` folder should do it.

**Pull request closed without merging**
